-- Inserare date în RECORD_LABEL
INSERT INTO RECORD_LABEL VALUES (SEQ_RECORD_LABEL.NEXTVAL, 'Universal Music', 'contact@universalmusic.com');
INSERT INTO RECORD_LABEL VALUES (SEQ_RECORD_LABEL.NEXTVAL, 'Sony Music', 'info@sonymusic.com');
INSERT INTO RECORD_LABEL VALUES (SEQ_RECORD_LABEL.NEXTVAL, 'Republic Records', 'office@republicrecords.com');
INSERT INTO RECORD_LABEL VALUES (SEQ_RECORD_LABEL.NEXTVAL, 'Atlantic Records', 'info@atlanticrecords.com');
INSERT INTO RECORD_LABEL VALUES (SEQ_RECORD_LABEL.NEXTVAL, 'Electrecord', 'contact@electrecord.ro');

-- Inserare date în PRODUCT (produse generale)
INSERT INTO PRODUCT VALUES (SEQ_PRODUCT.NEXTVAL, 49.99, TO_DATE('15/03/2022', 'DD/MM/YYYY'));
INSERT INTO PRODUCT VALUES (SEQ_PRODUCT.NEXTVAL, 49.99, TO_DATE('15/03/2022', 'DD/MM/YYYY'));
INSERT INTO PRODUCT VALUES (SEQ_PRODUCT.NEXTVAL, 39.99, TO_DATE('22/05/2022', 'DD/MM/YYYY'));
INSERT INTO PRODUCT VALUES (SEQ_PRODUCT.NEXTVAL, 29.99, TO_DATE('10/07/2022', 'DD/MM/YYYY'));
INSERT INTO PRODUCT VALUES (SEQ_PRODUCT.NEXTVAL, 19.99, TO_DATE('30/09/2022', 'DD/MM/YYYY'));
INSERT INTO PRODUCT VALUES (SEQ_PRODUCT.NEXTVAL, 59.99, TO_DATE('12/12/2022', 'DD/MM/YYYY'));
INSERT INTO PRODUCT VALUES (SEQ_PRODUCT.NEXTVAL, 34.99, TO_DATE('25/01/2023', 'DD/MM/YYYY'));
INSERT INTO PRODUCT VALUES (SEQ_PRODUCT.NEXTVAL, 44.99, TO_DATE('18/03/2023', 'DD/MM/YYYY'));
INSERT INTO PRODUCT VALUES (SEQ_PRODUCT.NEXTVAL, 24.99, TO_DATE('05/05/2023', 'DD/MM/YYYY'));
INSERT INTO PRODUCT VALUES (SEQ_PRODUCT.NEXTVAL, 64.99, TO_DATE('28/06/2023', 'DD/MM/YYYY'));
INSERT INTO PRODUCT VALUES (SEQ_PRODUCT.NEXTVAL, 54.99, TO_DATE('15/08/2023', 'DD/MM/YYYY'));

-- Inserare date în ALBUM
INSERT INTO ALBUM VALUES (1, 'Swimming', '49:07', 1);
INSERT INTO ALBUM VALUES (2, 'GNX', '42:11', 2);
INSERT INTO ALBUM VALUES (3, 'Short n Sweet', '42:19', 3);
INSERT INTO ALBUM VALUES (4, 'HUMBLE', '43:00', 4);
INSERT INTO ALBUM VALUES (5, 'folklore', '45:30', 5);
INSERT INTO ALBUM VALUES (6, 'the album', '30:45' , 5);

-- Inserare date în MERCHANDISE
INSERT INTO MERCHANDISE VALUES (6, 'T-Shirt', 'M');
INSERT INTO MERCHANDISE VALUES (7, 'Poster', NULL);
INSERT INTO MERCHANDISE VALUES (8, 'Cap', 'S');
INSERT INTO MERCHANDISE VALUES (9, 'Mug', NULL);
INSERT INTO MERCHANDISE VALUES (10, 'Hoodie', 'XL');

-- Inserare date în GENRE
INSERT INTO GENRE VALUES (SEQ_GENRE.NEXTVAL, 'RNB', 1);
INSERT INTO GENRE VALUES (SEQ_GENRE.NEXTVAL, 'Rap', 2);
INSERT INTO GENRE VALUES (SEQ_GENRE.NEXTVAL, 'Pop', 3);
INSERT INTO GENRE VALUES (SEQ_GENRE.NEXTVAL, 'Rap-RNB', 4);
INSERT INTO GENRE VALUES (SEQ_GENRE.NEXTVAL, 'Folk', 5);

-- Inserare date în ARTIST
INSERT INTO ARTIST VALUES (1, 'Mac', 'Miller', NULL);
INSERT INTO ARTIST VALUES (2, 'Kendrick', 'Lamar', NULL);
INSERT INTO ARTIST VALUES (3, 'Sabrina', 'Carpenter', NULL);
INSERT INTO ARTIST VALUES (4, 'Taylor', 'Swift', 'NULL');
INSERT INTO ARTIST VALUES (5, 'boygenius', 'boygenius', 'band');
INSERT INTO ARTIST VALUES (6, 'Rihanna', 'Rihanna', 'NULL');

-- Inserare date în PROVIDER
INSERT INTO PROVIDER VALUES (SEQ_PROVIDER.NEXTVAL, 'Music Distribution SRL', '07456123890', 'Str. Muzicii nr. 15, București');
INSERT INTO PROVIDER VALUES (SEQ_PROVIDER.NEXTVAL, 'Vinyl Factory', '07345678912', 'Calea Victoriei nr. 78, București');
INSERT INTO PROVIDER VALUES (SEQ_PROVIDER.NEXTVAL, 'Merch Production', '07234567891', 'Bd. Unirii nr. 45, București');
INSERT INTO PROVIDER VALUES (SEQ_PROVIDER.NEXTVAL, 'Global Logistics', '07123456789', 'Str. Industriilor nr. 12, Cluj-Napoca');
INSERT INTO PROVIDER VALUES (SEQ_PROVIDER.NEXTVAL, 'Record Distributor', '07987654321', 'Str. Republicii nr. 36, Timișoara');

-- Inserare date în MEDIA_FORMAT
INSERT INTO MEDIA_FORMAT VALUES (SEQ_MEDIA_FORMAT.NEXTVAL, 'CD', 1, 10);
INSERT INTO MEDIA_FORMAT VALUES (SEQ_MEDIA_FORMAT.NEXTVAL, 'Vinyl', 2, 20);
INSERT INTO MEDIA_FORMAT VALUES (SEQ_MEDIA_FORMAT.NEXTVAL, 'Digital', 3, 0);
INSERT INTO MEDIA_FORMAT VALUES (SEQ_MEDIA_FORMAT.NEXTVAL, 'Cassette', 4, 5);
INSERT INTO MEDIA_FORMAT VALUES (SEQ_MEDIA_FORMAT.NEXTVAL, 'CD', 5, 10);

-- Inserare date în FUNCTION
INSERT INTO FUNCTION VALUES (SEQ_FUNCTION.NEXTVAL, 'Manager', 5000, 8000);
INSERT INTO FUNCTION VALUES (SEQ_FUNCTION.NEXTVAL, 'Sales Representative', 3000, 5000);
INSERT INTO FUNCTION VALUES (SEQ_FUNCTION.NEXTVAL, 'Cashier', 2500, 3500);
INSERT INTO FUNCTION VALUES (SEQ_FUNCTION.NEXTVAL, 'Marketing Specialist', 4000, 6000);
INSERT INTO FUNCTION VALUES (SEQ_FUNCTION.NEXTVAL, 'Store Assistant', 2000, 3000);

-- Inserare date în EMPLOYEE
INSERT INTO EMPLOYEE VALUES (SEQ_EMPLOYEE.NEXTVAL, 1, 'Popescu', 'Maria', '07123456789', TO_DATE('15/01/2020', 'DD/MM/YYYY'), 6500);
INSERT INTO EMPLOYEE VALUES (SEQ_EMPLOYEE.NEXTVAL, 2, 'Ionescu', 'Andrei', '07234567890', TO_DATE('10/03/2020', 'DD/MM/YYYY'), 4000);
INSERT INTO EMPLOYEE VALUES (SEQ_EMPLOYEE.NEXTVAL, 3, 'Popa', 'Elena', '07345678901', TO_DATE('22/05/2021', 'DD/MM/YYYY'), 3000);
INSERT INTO EMPLOYEE VALUES (SEQ_EMPLOYEE.NEXTVAL, 4, 'Georgescu', 'Mihai', '07456789012', TO_DATE('17/08/2021', 'DD/MM/YYYY'), 5000);
INSERT INTO EMPLOYEE VALUES (SEQ_EMPLOYEE.NEXTVAL, 5, 'Stanciu', 'Cristina', '07567890123', TO_DATE('05/12/2021', 'DD/MM/YYYY'), 2500);

-- Inserare date în CUSTOMER
INSERT INTO CUSTOMER VALUES (SEQ_CUSTOMER.NEXTVAL, 'Dumitrescu', 'Alexandru', 'Str. Libertății nr. 10, București', 'București');
INSERT INTO CUSTOMER VALUES (SEQ_CUSTOMER.NEXTVAL, 'Radu', 'Ioana', 'Str. Unirii nr. 25, Cluj-Napoca', 'Cluj-Napoca');
INSERT INTO CUSTOMER VALUES (SEQ_CUSTOMER.NEXTVAL, 'Stoica', 'Gabriel', 'Bd. Independenței nr. 15, Iași', 'Iași');
INSERT INTO CUSTOMER VALUES (SEQ_CUSTOMER.NEXTVAL, 'Munteanu', 'Diana', 'Str. Mihai Viteazul nr. 8, Timișoara', 'Timișoara');
INSERT INTO CUSTOMER VALUES (SEQ_CUSTOMER.NEXTVAL, 'Dinu', 'Bogdan', 'Str. Primăverii nr. 12, Brașov', 'Brașov');

-- Inserare date în STOCK
INSERT INTO STOCK VALUES (SEQ_STOCK.NEXTVAL, 1, 1, 50);
INSERT INTO STOCK VALUES (SEQ_STOCK.NEXTVAL, 2, 2, 30);
INSERT INTO STOCK VALUES (SEQ_STOCK.NEXTVAL, 3, 1, 100);
INSERT INTO STOCK VALUES (SEQ_STOCK.NEXTVAL, 4, 2, 20);
INSERT INTO STOCK VALUES (SEQ_STOCK.NEXTVAL, 5, 1, 40);
INSERT INTO STOCK VALUES (SEQ_STOCK.NEXTVAL, 6, 3, 75);
INSERT INTO STOCK VALUES (SEQ_STOCK.NEXTVAL, 7, 3, 60);
INSERT INTO STOCK VALUES (SEQ_STOCK.NEXTVAL, 8, 3, 90);
INSERT INTO STOCK VALUES (SEQ_STOCK.NEXTVAL, 9, 3, 45);
INSERT INTO STOCK VALUES (SEQ_STOCK.NEXTVAL, 10, 3, 30);

-- Inserare date în PURCHASE
INSERT INTO PURCHASE VALUES (SEQ_PURCHASE.NEXTVAL, 1, 2, 1, TO_DATE('20/04/2023', 'DD/MM/YYYY'), 'Card', 'Completed', 1);
INSERT INTO PURCHASE VALUES (SEQ_PURCHASE.NEXTVAL, 2, 2, 3, TO_DATE('25/04/2023', 'DD/MM/YYYY'), 'Cash', 'Completed', 1);
INSERT INTO PURCHASE VALUES (SEQ_PURCHASE.NEXTVAL, 3, 3, 6, TO_DATE('30/04/2023', 'DD/MM/YYYY'), 'Card', 'Completed', 2);
INSERT INTO PURCHASE VALUES (SEQ_PURCHASE.NEXTVAL, 4, 2, 2, TO_DATE('05/05/2023', 'DD/MM/YYYY'), 'Card', 'Pending', 1);
INSERT INTO PURCHASE VALUES (SEQ_PURCHASE.NEXTVAL, 5, 3, 8, TO_DATE('10/05/2023', 'DD/MM/YYYY'), 'Cash', 'Pending', 3);
INSERT INTO PURCHASE VALUES (SEQ_PURCHASE.NEXTVAL, 1, 2, 5, TO_DATE('15/05/2023', 'DD/MM/YYYY'), 'Card', 'Completed', 1);
INSERT INTO PURCHASE VALUES (SEQ_PURCHASE.NEXTVAL, 2, 3, 10, TO_DATE('20/05/2023', 'DD/MM/YYYY'), 'Cash', 'Cancelled', 1);
INSERT INTO PURCHASE VALUES (SEQ_PURCHASE.NEXTVAL, 3, 2, 4, TO_DATE('25/05/2023', 'DD/MM/YYYY'), 'Card', 'Completed', 1);

-- Inserare date în SONG
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 1, 1, 'Self Care', '5:01');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 1, 1, 'Come back to earth', '3:39');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 2, 2, 'luther', '4:15');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 2, 2, 'heart pt. 6', '5:10');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 3, 3, 'Taste', '4:54');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 3, 3, 'Please Please Please', '5:57');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 4, 6, 'HUMBLE', '6:22');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 4, 2, 'DNA', '7:06');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 4, 4, 'the one', '3:45');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 4, 5, 'the lakes', '4:20');

COMMIT;