-- Inserare date în RECORD_LABEL
INSERT INTO RECORD_LABEL VALUES (SEQ_RECORD_LABEL.NEXTVAL, 'Universal Music', 'contact@universalmusic.com');
INSERT INTO RECORD_LABEL VALUES (SEQ_RECORD_LABEL.NEXTVAL, 'Sony Music', 'info@sonymusic.com');
INSERT INTO RECORD_LABEL VALUES (SEQ_RECORD_LABEL.NEXTVAL, 'Republic Records', 'office@republicrecords.com');
INSERT INTO RECORD_LABEL VALUES (SEQ_RECORD_LABEL.NEXTVAL, 'Atlantic Records', 'info@atlanticrecords.com');
INSERT INTO RECORD_LABEL VALUES (SEQ_RECORD_LABEL.NEXTVAL, 'Electrecord', 'contact@electrecord.ro');
INSERT INTO RECORD_LABEL VALUES (SEQ_RECORD_LABEL.NEXTVAL, 'Def Jam Recordings', 'contact@defjam.com');
INSERT INTO RECORD_LABEL VALUES (SEQ_RECORD_LABEL.NEXTVAL, 'Interscope Records', 'info@interscope.com');

-- Inserare date în PRODUCT (produse generale)
INSERT INTO PRODUCT VALUES (SEQ_PRODUCT.NEXTVAL, 49.99, TO_DATE('15/03/2022', 'DD/MM/YYYY'));  -- 1
INSERT INTO PRODUCT VALUES (SEQ_PRODUCT.NEXTVAL, 49.99, TO_DATE('15/03/2022', 'DD/MM/YYYY'));  -- 2
INSERT INTO PRODUCT VALUES (SEQ_PRODUCT.NEXTVAL, 39.99, TO_DATE('22/05/2022', 'DD/MM/YYYY'));  -- 3
INSERT INTO PRODUCT VALUES (SEQ_PRODUCT.NEXTVAL, 29.99, TO_DATE('10/07/2022', 'DD/MM/YYYY'));  -- 4
INSERT INTO PRODUCT VALUES (SEQ_PRODUCT.NEXTVAL, 19.99, TO_DATE('30/09/2022', 'DD/MM/YYYY'));  -- 5
INSERT INTO PRODUCT VALUES (SEQ_PRODUCT.NEXTVAL, 59.99, TO_DATE('12/12/2022', 'DD/MM/YYYY'));  -- 6
INSERT INTO PRODUCT VALUES (SEQ_PRODUCT.NEXTVAL, 34.99, TO_DATE('25/01/2023', 'DD/MM/YYYY'));  -- 7
INSERT INTO PRODUCT VALUES (SEQ_PRODUCT.NEXTVAL, 44.99, TO_DATE('18/03/2023', 'DD/MM/YYYY'));  -- 8
INSERT INTO PRODUCT VALUES (SEQ_PRODUCT.NEXTVAL, 24.99, TO_DATE('05/05/2023', 'DD/MM/YYYY'));  -- 9
INSERT INTO PRODUCT VALUES (SEQ_PRODUCT.NEXTVAL, 64.99, TO_DATE('28/06/2023', 'DD/MM/YYYY'));  -- 10
INSERT INTO PRODUCT VALUES (SEQ_PRODUCT.NEXTVAL, 54.99, TO_DATE('15/08/2023', 'DD/MM/YYYY'));  -- 11
INSERT INTO PRODUCT VALUES (SEQ_PRODUCT.NEXTVAL, 52.99, TO_DATE('15/09/2023', 'DD/MM/YYYY'));  -- 12
INSERT INTO PRODUCT VALUES (SEQ_PRODUCT.NEXTVAL, 47.99, TO_DATE('25/10/2023', 'DD/MM/YYYY'));  -- 13
INSERT INTO PRODUCT VALUES (SEQ_PRODUCT.NEXTVAL, 22.99, TO_DATE('08/11/2023', 'DD/MM/YYYY'));  -- 14
INSERT INTO PRODUCT VALUES (SEQ_PRODUCT.NEXTVAL, 37.99, TO_DATE('01/12/2023', 'DD/MM/YYYY'));  -- 15
INSERT INTO PRODUCT VALUES (SEQ_PRODUCT.NEXTVAL, 42.99, TO_DATE('15/01/2024', 'DD/MM/YYYY'));  -- 16

-- Inserare date în ALBUM
INSERT INTO ALBUM VALUES (1, 'Swimming', '49:07', 1);
INSERT INTO ALBUM VALUES (2, 'GNX', '42:11', 2);
INSERT INTO ALBUM VALUES (3, 'Short n Sweet', '42:19', 3);
INSERT INTO ALBUM VALUES (4, 'HUMBLE', '43:00', 4);
INSERT INTO ALBUM VALUES (5, 'folklore', '45:30', 5);
INSERT INTO ALBUM VALUES (11, 'the album', '30:45', 1);
INSERT INTO ALBUM VALUES (12, 'Blonde', '60:08', 3);
INSERT INTO ALBUM VALUES (13, 'DAMN.', '54:54', 4);
INSERT INTO ALBUM VALUES (15, 'After Hours', '56:19', 6);
INSERT INTO ALBUM VALUES (16, 'Happier Than Ever', '56:15', 7);

-- Inserare date în MERCHANDISE
INSERT INTO MERCHANDISE VALUES (6, 'T-Shirt', 'M');
INSERT INTO MERCHANDISE VALUES (7, 'Poster', NULL);
INSERT INTO MERCHANDISE VALUES (8, 'Cap', 'S');
INSERT INTO MERCHANDISE VALUES (9, 'Mug', NULL);
INSERT INTO MERCHANDISE VALUES (10, 'Hoodie', 'XL');
INSERT INTO MERCHANDISE VALUES (14, 'Vinyl Stand', NULL);

-- Inserare date în GENRE (cu genuri unice)
INSERT INTO GENRE VALUES (SEQ_GENRE.NEXTVAL, 'RnB', 1);
INSERT INTO GENRE VALUES (SEQ_GENRE.NEXTVAL, 'Rap', 2);
INSERT INTO GENRE VALUES (SEQ_GENRE.NEXTVAL, 'Pop', 3);
INSERT INTO GENRE VALUES (SEQ_GENRE.NEXTVAL, 'Rap-RNB', 4);
INSERT INTO GENRE VALUES (SEQ_GENRE.NEXTVAL, 'Folk', 5);
INSERT INTO GENRE VALUES (SEQ_GENRE.NEXTVAL, 'Hip-Hop', 2);
INSERT INTO GENRE VALUES (SEQ_GENRE.NEXTVAL, 'Alternative', 12);
INSERT INTO GENRE VALUES (SEQ_GENRE.NEXTVAL, 'Indie', 5);
INSERT INTO GENRE VALUES (SEQ_GENRE.NEXTVAL, 'Electronic', 15);
INSERT INTO GENRE VALUES (SEQ_GENRE.NEXTVAL, 'Alternative Pop', 16);

-- Inserare date în ARTIST
INSERT INTO ARTIST VALUES (SEQ_ARTIST.NEXTVAL, 'Mac', 'Miller', NULL);
INSERT INTO ARTIST VALUES (SEQ_ARTIST.NEXTVAL, 'Kendrick', 'Lamar', NULL);
INSERT INTO ARTIST VALUES (SEQ_ARTIST.NEXTVAL, 'Sabrina', 'Carpenter', NULL);
INSERT INTO ARTIST VALUES (SEQ_ARTIST.NEXTVAL, 'Taylor', 'Swift', NULL);
INSERT INTO ARTIST VALUES (SEQ_ARTIST.NEXTVAL, 'boygenius', 'boygenius', 'band');
INSERT INTO ARTIST VALUES (SEQ_ARTIST.NEXTVAL, 'Rihanna', NULL, NULL);
INSERT INTO ARTIST VALUES (SEQ_ARTIST.NEXTVAL, 'Frank', 'Ocean', NULL);
INSERT INTO ARTIST VALUES (SEQ_ARTIST.NEXTVAL, 'Billie', 'Eilish', NULL);
INSERT INTO ARTIST VALUES (SEQ_ARTIST.NEXTVAL, 'The Weeknd', NULL, NULL);
INSERT INTO ARTIST VALUES (SEQ_ARTIST.NEXTVAL, 'SZA', NULL, NULL);

-- Inserare date în PROVIDER
INSERT INTO PROVIDER VALUES (SEQ_PROVIDER.NEXTVAL, 'Music Distribution SRL', '07456123890', 'Str. Muzicii nr. 15, București');
INSERT INTO PROVIDER VALUES (SEQ_PROVIDER.NEXTVAL, 'Vinyl Factory', '07345678912', 'Calea Victoriei nr. 78, București');
INSERT INTO PROVIDER VALUES (SEQ_PROVIDER.NEXTVAL, 'Merch Production', '07234567891', 'Bd. Unirii nr. 45, București');
INSERT INTO PROVIDER VALUES (SEQ_PROVIDER.NEXTVAL, 'Global Logistics', '07123456789', 'Str. Industriilor nr. 12, Cluj-Napoca');
INSERT INTO PROVIDER VALUES (SEQ_PROVIDER.NEXTVAL, 'Record Distributor', '07987654321', 'Str. Republicii nr. 36, Timișoara');
INSERT INTO PROVIDER VALUES (SEQ_PROVIDER.NEXTVAL, 'Audio Tech SRL', '07765432109', 'Str. Aviatiei nr. 24, București');
INSERT INTO PROVIDER VALUES (SEQ_PROVIDER.NEXTVAL, 'Music Warehouse', '07654321098', 'Calea Floreasca nr. 55, București');

-- Inserare date în MEDIA_FORMAT (formate diverse)
INSERT INTO MEDIA_FORMAT VALUES (SEQ_MEDIA_FORMAT.NEXTVAL, 'CD', 1, 10);
INSERT INTO MEDIA_FORMAT VALUES (SEQ_MEDIA_FORMAT.NEXTVAL, 'Vinyl', 1, 25);
INSERT INTO MEDIA_FORMAT VALUES (SEQ_MEDIA_FORMAT.NEXTVAL, 'Cassette', 1, 25);
INSERT INTO MEDIA_FORMAT VALUES (SEQ_MEDIA_FORMAT.NEXTVAL, 'Digital', 1, 25);

INSERT INTO MEDIA_FORMAT VALUES (SEQ_MEDIA_FORMAT.NEXTVAL, 'Vinyl', 2, 20);

INSERT INTO MEDIA_FORMAT VALUES (SEQ_MEDIA_FORMAT.NEXTVAL, 'Digital', 3, 0);
INSERT INTO MEDIA_FORMAT VALUES (SEQ_MEDIA_FORMAT.NEXTVAL, 'CD', 3, 0);

INSERT INTO MEDIA_FORMAT VALUES (SEQ_MEDIA_FORMAT.NEXTVAL, 'Cassette', 4, 5);

INSERT INTO MEDIA_FORMAT VALUES (SEQ_MEDIA_FORMAT.NEXTVAL, 'Digital', 5, 0);
INSERT INTO MEDIA_FORMAT VALUES (SEQ_MEDIA_FORMAT.NEXTVAL, 'Vinyl', 5, 25);
INSERT INTO MEDIA_FORMAT VALUES (SEQ_MEDIA_FORMAT.NEXTVAL, 'Cassette', 5, 10);

INSERT INTO MEDIA_FORMAT VALUES (SEQ_MEDIA_FORMAT.NEXTVAL, 'Digital', 11, 0);

INSERT INTO MEDIA_FORMAT VALUES (SEQ_MEDIA_FORMAT.NEXTVAL, 'Digital', 12, 0);
INSERT INTO MEDIA_FORMAT VALUES (SEQ_MEDIA_FORMAT.NEXTVAL, 'Vinyl', 12, 25);

INSERT INTO MEDIA_FORMAT VALUES (SEQ_MEDIA_FORMAT.NEXTVAL, 'Cassette', 13, 10);

INSERT INTO MEDIA_FORMAT VALUES (SEQ_MEDIA_FORMAT.NEXTVAL, 'Digital', 15, 0);
INSERT INTO MEDIA_FORMAT VALUES (SEQ_MEDIA_FORMAT.NEXTVAL, 'CD', 15, 15);

INSERT INTO MEDIA_FORMAT VALUES (SEQ_MEDIA_FORMAT.NEXTVAL, 'Digital', 16, 0);
INSERT INTO MEDIA_FORMAT VALUES (SEQ_MEDIA_FORMAT.NEXTVAL, 'Vinyl 7"', 16, 20);

-- Inserare date în FUNCTION
INSERT INTO FUNCTION VALUES (SEQ_FUNCTION.NEXTVAL, 'Manager', 5000, 8000);
INSERT INTO FUNCTION VALUES (SEQ_FUNCTION.NEXTVAL, 'Sales Representative', 3000, 5000);
INSERT INTO FUNCTION VALUES (SEQ_FUNCTION.NEXTVAL, 'Cashier', 2500, 3500);
INSERT INTO FUNCTION VALUES (SEQ_FUNCTION.NEXTVAL, 'Marketing Specialist', 4000, 6000);
INSERT INTO FUNCTION VALUES (SEQ_FUNCTION.NEXTVAL, 'Store Assistant', 2000, 3000);
INSERT INTO FUNCTION VALUES (SEQ_FUNCTION.NEXTVAL, 'IT Support', 3500, 5500);
INSERT INTO FUNCTION VALUES (SEQ_FUNCTION.NEXTVAL, 'Inventory Manager', 4500, 6500);

-- Inserare date în EMPLOYEE
INSERT INTO EMPLOYEE VALUES (SEQ_EMPLOYEE.NEXTVAL, 1, 'Popescu', 'Maria', '07123456789', TO_DATE('15/01/2020', 'DD/MM/YYYY'), 6500);
INSERT INTO EMPLOYEE VALUES (SEQ_EMPLOYEE.NEXTVAL, 2, 'Ionescu', 'Andrei', '07234567890', TO_DATE('10/03/2020', 'DD/MM/YYYY'), 4000);
INSERT INTO EMPLOYEE VALUES (SEQ_EMPLOYEE.NEXTVAL, 3, 'Popa', 'Elena', '07345678901', TO_DATE('22/05/2021', 'DD/MM/YYYY'), 3000);
INSERT INTO EMPLOYEE VALUES (SEQ_EMPLOYEE.NEXTVAL, 4, 'Georgescu', 'Mihai', '07456789012', TO_DATE('17/08/2021', 'DD/MM/YYYY'), 5000);
INSERT INTO EMPLOYEE VALUES (SEQ_EMPLOYEE.NEXTVAL, 5, 'Stanciu', 'Cristina', '07567890123', TO_DATE('05/12/2021', 'DD/MM/YYYY'), 2500);
INSERT INTO EMPLOYEE VALUES (SEQ_EMPLOYEE.NEXTVAL, 6, 'Dumitrache', 'Alexandru', '07678901234', TO_DATE('10/02/2022', 'DD/MM/YYYY'), 4500);
INSERT INTO EMPLOYEE VALUES (SEQ_EMPLOYEE.NEXTVAL, 7, 'Marinescu', 'Diana', '07789012345', TO_DATE('18/04/2022', 'DD/MM/YYYY'), 5500);

-- Inserare date în CUSTOMER
INSERT INTO CUSTOMER VALUES (SEQ_CUSTOMER.NEXTVAL, 'Dumitrescu', 'Alexandru', 'Str. Libertății nr. 10, București', 'București');
INSERT INTO CUSTOMER VALUES (SEQ_CUSTOMER.NEXTVAL, 'Radu', 'Ioana', 'Str. Unirii nr. 25, Cluj-Napoca', 'Cluj-Napoca');
INSERT INTO CUSTOMER VALUES (SEQ_CUSTOMER.NEXTVAL, 'Stoica', 'Gabriel', 'Bd. Independenței nr. 15, Iași', 'Iași');
INSERT INTO CUSTOMER VALUES (SEQ_CUSTOMER.NEXTVAL, 'Munteanu', 'Diana', 'Str. Mihai Viteazul nr. 8, Timișoara', 'Timișoara');
INSERT INTO CUSTOMER VALUES (SEQ_CUSTOMER.NEXTVAL, 'Dinu', 'Bogdan', 'Str. Primăverii nr. 12, Brașov', 'Brașov');
INSERT INTO CUSTOMER VALUES (SEQ_CUSTOMER.NEXTVAL, 'Vasile', 'Andreea', 'Str. Florilor nr. 5, Constanța', 'Constanța');
INSERT INTO CUSTOMER VALUES (SEQ_CUSTOMER.NEXTVAL, 'Preda', 'Robert', 'Str. Tudor Vladimirescu nr. 18, Craiova', 'Craiova');
INSERT INTO CUSTOMER VALUES (SEQ_CUSTOMER.NEXTVAL, 'Manole', 'Cristina', 'Str. Mioritei nr. 7, Sibiu', 'Sibiu');

-- Inserare date în STOCK
INSERT INTO STOCK VALUES (SEQ_STOCK.NEXTVAL, 1, 1, 50);
INSERT INTO STOCK VALUES (SEQ_STOCK.NEXTVAL, 1, 3, 50);
INSERT INTO STOCK VALUES (SEQ_STOCK.NEXTVAL, 2, 2, 30);
INSERT INTO STOCK VALUES (SEQ_STOCK.NEXTVAL, 2, 7, 30);
INSERT INTO STOCK VALUES (SEQ_STOCK.NEXTVAL, 2, 5, 70);
INSERT INTO STOCK VALUES (SEQ_STOCK.NEXTVAL, 3, 1, 100);
INSERT INTO STOCK VALUES (SEQ_STOCK.NEXTVAL, 4, 2, 20);
INSERT INTO STOCK VALUES (SEQ_STOCK.NEXTVAL, 5, 1, 40);
INSERT INTO STOCK VALUES (SEQ_STOCK.NEXTVAL, 6, 3, 75);
INSERT INTO STOCK VALUES (SEQ_STOCK.NEXTVAL, 7, 3, 60);
INSERT INTO STOCK VALUES (SEQ_STOCK.NEXTVAL, 8, 3, 90);
INSERT INTO STOCK VALUES (SEQ_STOCK.NEXTVAL, 9, 3, 45);
INSERT INTO STOCK VALUES (SEQ_STOCK.NEXTVAL, 10, 3, 30);
INSERT INTO STOCK VALUES (SEQ_STOCK.NEXTVAL, 11, 1, 25);
INSERT INTO STOCK VALUES (SEQ_STOCK.NEXTVAL, 12, 2, 15);
INSERT INTO STOCK VALUES (SEQ_STOCK.NEXTVAL, 13, 1, 35);
INSERT INTO STOCK VALUES (SEQ_STOCK.NEXTVAL, 14, 3, 50);
INSERT INTO STOCK VALUES (SEQ_STOCK.NEXTVAL, 15, 2, 40);
INSERT INTO STOCK VALUES (SEQ_STOCK.NEXTVAL, 15, 4, 60);
INSERT INTO STOCK VALUES (SEQ_STOCK.NEXTVAL, 15, 5, 70);
INSERT INTO STOCK VALUES (SEQ_STOCK.NEXTVAL, 16, 1, 30);

-- Inserare date în PURCHASE
INSERT INTO PURCHASE VALUES (SEQ_PURCHASE.NEXTVAL, 1, 2, 1, TO_DATE('20/04/2023', 'DD/MM/YYYY'), 'Card', 'Completed', 1);
INSERT INTO PURCHASE VALUES (SEQ_PURCHASE.NEXTVAL, 2, 2, 3, TO_DATE('25/04/2023', 'DD/MM/YYYY'), 'Cash', 'Completed', 1);
INSERT INTO PURCHASE VALUES (SEQ_PURCHASE.NEXTVAL, 3, 3, 6, TO_DATE('30/04/2023', 'DD/MM/YYYY'), 'Card', 'Completed', 2);
INSERT INTO PURCHASE VALUES (SEQ_PURCHASE.NEXTVAL, 4, 2, 2, TO_DATE('05/05/2023', 'DD/MM/YYYY'), 'Card', 'Pending', 1);
INSERT INTO PURCHASE VALUES (SEQ_PURCHASE.NEXTVAL, 5, 3, 8, TO_DATE('10/05/2023', 'DD/MM/YYYY'), 'Cash', 'Pending', 3);
INSERT INTO PURCHASE VALUES (SEQ_PURCHASE.NEXTVAL, 1, 2, 5, TO_DATE('15/05/2023', 'DD/MM/YYYY'), 'Card', 'Completed', 1);
INSERT INTO PURCHASE VALUES (SEQ_PURCHASE.NEXTVAL, 2, 3, 10, TO_DATE('20/05/2023', 'DD/MM/YYYY'), 'Cash', 'Cancelled', 1);
INSERT INTO PURCHASE VALUES (SEQ_PURCHASE.NEXTVAL, 3, 2, 4, TO_DATE('25/05/2023', 'DD/MM/YYYY'), 'Card', 'Completed', 1);
INSERT INTO PURCHASE VALUES (SEQ_PURCHASE.NEXTVAL, 6, 4, 12, TO_DATE('02/06/2023', 'DD/MM/YYYY'), 'Card', 'Completed', 1);
INSERT INTO PURCHASE VALUES (SEQ_PURCHASE.NEXTVAL, 7, 5, 13, TO_DATE('10/06/2023', 'DD/MM/YYYY'), 'Cash', 'Completed', 2);
INSERT INTO PURCHASE VALUES (SEQ_PURCHASE.NEXTVAL, 8, 2, 15, TO_DATE('18/06/2023', 'DD/MM/YYYY'), 'Card', 'Pending', 1);
INSERT INTO PURCHASE VALUES (SEQ_PURCHASE.NEXTVAL, 4, 3, 11, TO_DATE('25/06/2023', 'DD/MM/YYYY'), 'Cash', 'Completed', 1);

-- Inserare date în SONG
-- Inserare in id_album=1
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 1, 1, 'Come Back to Earth', '2:41');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 1, 1, 'Hurt Feelings', '4:05');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 1, 1, 'What''s the Use?', '4:48');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 1, 1, 'Perfecto', '3:35');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 1, 1, 'Self Care', '5:45');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 1, 1, 'Wings', '4:10');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 1, 1, 'Ladders', '4:47');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 1, 1, 'Small Worlds', '4:31');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 1, 1, 'Conversation Pt. 1', '3:30');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 1, 1, 'Dunno', '3:57');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 1, 1, 'Jet Fuel', '5:45');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 1, 1, '2009', '5:47');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 1, 1, 'So It Goes', '5:12');

-- Inserare in album cu id_product = 2 
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 2, 2, 'wacced out murals', '5:17');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 2, 2, 'squabble up', '2:37');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 10, 2, 'luther (with sza)', '2:57');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 2, 2, 'luther (with sza)', '2:57'); --adaugat de 2 ori dar cu artisti diferiti pentru a oferi credite amandoi artistilor
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 2, 2, 'man at the garden', '3:53');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 2, 2, 'hey now (feat. dody6)', '3:37');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 2, 2, 'reincarnated', '4:35');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 2, 2, 'tv off (feat. hefty gunplay)', '3:40');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 2, 2, 'dodger blue (feat. wallie the...)', '2:11'); 
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 2, 2, 'peekaboo (feat. azchike)', '2:35');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 2, 2, 'heart pt. 6', '4:52'); 

-- Inserare in album cu id_product = 3
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 3, 3, 'Taste', '4:54');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 3, 3, 'Please Please Please', '5:57');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 3, 3, 'Good Graces', '3:05');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 3, 3, 'Sharpest Tool', '3:38');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 3, 3, 'Coincidence', '2:44');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 3, 3, 'Bed Chem', '2:51');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 3, 3, 'Espresso', '2:55');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 3, 3, 'Dumb n Poetic', '2:13');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 3, 3, 'Slim Pickins', '2:32');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 3, 3, 'Juno', '3:43');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 3, 3, 'Lie to girls', '3:22');

INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 2, 4, 'BLOOD.', '1:58');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 2, 4, 'DNA', '3:05');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 2, 4, 'YAH.', '2:40');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 2, 4, 'ELEMENT.', '3:28');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 2, 4, 'FEEL.', '3:34');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 2, 4, 'LOYALTY.', '3:47');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 6, 4, 'LOYALTY.', '3:47');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 2, 4, 'PRIDE.', '4:35');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 2, 4, 'HUMBLE', '6:22');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 2, 4, 'LUST.', '5:07');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 2, 4, 'LOVE.', '3:33');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 2, 4, 'XXX.', '4:14');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 2, 4, 'FEAR.', '7:40');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 2, 4, 'GOD.', '4:08');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 2, 4, 'DUCKWORTH.', '4:08');

INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 4, 5, 'cardigan', '3:59');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 4, 5, 'august', '4:21');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 4, 5, 'exile (featuring Bon Iver)', '4:45');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 4, 5, 'my tears ricochet', '4:15');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 4, 5, 'mirrorball', '3:29');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 4, 5, 'seven', '3:28');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 4, 5, 'this is me trying', '3:15');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 4, 5, 'illicit affairs', '3:10');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 4, 5, 'betty', '4:54');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 4, 5, 'peace', '5:23');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 4, 5, 'hoax', '3:40');

INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 4, 11, 'two', '3:12');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 4, 11, 'three', '2:57');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 4, 11, 'four', '3:22');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 4, 11, 'five', '4:01');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 4, 11, 'six', '3:44');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 4, 11, 'seven', '3:18');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 4, 11, 'eight', '2:55');


INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 7, 12, 'Pink + White', '3:04');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 7, 12, 'Solo', '4:17');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 7, 12, 'Self Control', '4:09');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 7, 12, 'Nights', '5:07');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 7, 12, 'White Ferrari', '4:08');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 7, 12, 'Godspeed', '2:57');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 7, 12, 'Futura Free', '9:24');

INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 2, 13, 'BLOOD.', '1:58');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 2, 13, 'DNA.', '3:05');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 2, 13, 'ELEMENT.', '3:28');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 2, 13, 'FEEL.', '3:34');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 2, 13, 'HUMBLE.', '2:57');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 2, 13, 'XXX.', '4:14');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 2, 13, 'FEAR.', '7:40');

INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 9, 15, 'After Hours', '6:01');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 9, 15, 'Heartless', '3:18');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 9, 15, 'In Your Eyes', '3:57');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 9, 15, 'Too Late', '3:59');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 9, 15, 'Hardest To Love', '3:31');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 9, 15, 'Scared To Live', '3:11');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 9, 15, 'Snowchild', '4:07');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 9, 15, 'Escape From LA', '5:55');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 9, 15, 'Faith', '4:43');


INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 8, 16, 'Therefore I Am', '2:54');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 8, 16, 'Your Power', '4:05');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 8, 16, 'Lost Cause', '3:32');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 8, 16, 'my future', '3:30');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 8, 16, 'Oxytocin', '3:30');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 8, 16, 'GOLDWING', '2:31');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 8, 16, 'Billie Bossa Nova', '3:16');
INSERT INTO SONG VALUES (SEQ_SONG.NEXTVAL, 8, 16, 'Getting Older', '4:04');

COMMIT;

