--1. Numele și salariul colegilor lui Gates (din același departament), excluzându-l pe el
SELECT FIRST_NAME, LAST_NAME, SALARY
FROM EMPLOYEES
WHERE DEPARTMENT_ID = (
  SELECT DEPARTMENT_ID FROM EMPLOYEES WHERE LAST_NAME = 'Gates'
)
AND LAST_NAME <> 'Gates';

-- 2. Codul, numele, salariul angajatului + numele șefului său direct
SELECT e.EMPLOYEE_ID, e.FIRST_NAME, e.LAST_NAME, e.SALARY,
       m.FIRST_NAME AS MANAGER_FIRST, m.LAST_NAME AS MANAGER_LAST
FROM EMPLOYEES e
LEFT JOIN EMPLOYEES m ON e.MANAGER_ID = m.EMPLOYEE_ID;

-- 3. Angajați care câștigă mai mult decât oricare „CLERK”, excluzându-se pe ei înșiși
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY > ANY (
    SELECT SALARY FROM EMPLOYEES WHERE JOB_ID LIKE '%CLERK%'
)
AND JOB_ID NOT LIKE '%CLERK%'
ORDER BY SALARY DESC;

-- 4. Angajați fără comision dar cu șef care are comision
SELECT e.FIRST_NAME, e.LAST_NAME, e.SALARY
FROM EMPLOYEES e
JOIN EMPLOYEES m ON e.MANAGER_ID = m.EMPLOYEE_ID
WHERE e.COMMISSION_PCT IS NULL AND m.COMMISSION_PCT IS NOT NULL;

-- 5. Cel mai vechi angajat din fiecare departament
SELECT e.FIRST_NAME, e.LAST_NAME, e.HIRE_DATE, e.DEPARTMENT_ID, d.DEPARTMENT_NAME
FROM EMPLOYEES e
JOIN DEPARTMENTS d ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
WHERE e.HIRE_DATE = (
  SELECT MIN(HIRE_DATE)
  FROM EMPLOYEES
  WHERE DEPARTMENT_ID = e.DEPARTMENT_ID
)
ORDER BY d.DEPARTMENT_NAME;

-- 6. Angajați care au același salariu și departament cu cineva care primește comision (excluzându-se pe ei)
SELECT FIRST_NAME, LAST_NAME, DEPARTMENT_ID, SALARY
FROM EMPLOYEES e
WHERE (DEPARTMENT_ID, SALARY) IN (
  SELECT DEPARTMENT_ID, SALARY
  FROM EMPLOYEES
  WHERE COMMISSION_PCT IS NOT NULL
)
AND COMMISSION_PCT IS NULL;

-- 7. Angajați conduși direct de președinte + numele colegului cu cel mai mare salariu din departament
SELECT e.FIRST_NAME, e.LAST_NAME, e.SALARY,
  (SELECT FIRST_NAME || ' ' || LAST_NAME
   FROM EMPLOYEES
   WHERE DEPARTMENT_ID = e.DEPARTMENT_ID
     AND SALARY = (
       SELECT MAX(SALARY)
       FROM EMPLOYEES
       WHERE DEPARTMENT_ID = e.DEPARTMENT_ID
     )
   FETCH FIRST 1 ROWS ONLY
  ) AS TOP_COLLEAGUE
FROM EMPLOYEES e
WHERE e.MANAGER_ID = (
  SELECT EMPLOYEE_ID
  FROM EMPLOYEES
  WHERE MANAGER_ID IS NULL
);

-- 8. Numele primilor 7 angajați cu salariul maxim, ordonat crescător
SELECT FIRST_NAME, LAST_NAME, SALARY
FROM (
  SELECT DISTINCT FIRST_NAME, LAST_NAME, SALARY
  FROM EMPLOYEES
  ORDER BY SALARY DESC
)
WHERE ROWNUM <= 7
ORDER BY SALARY;

-- 9. Angajați care câștigă unul dintre cele mai mari 7 salarii
SELECT FIRST_NAME, LAST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY IN (
  SELECT DISTINCT SALARY
  FROM EMPLOYEES
  ORDER BY SALARY DESC
)
AND ROWNUM <= 7
ORDER BY SALARY;


-- 10. Angajații care câștigă al 7-lea salariu ca mărime
SELECT FIRST_NAME, LAST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY = (
  SELECT MIN(SALARY)
  FROM (
    SELECT DISTINCT SALARY
    FROM EMPLOYEES
    ORDER BY SALARY DESC
    FETCH FIRST 7 ROWS ONLY
  )
);


--scraps
SELECT FIRST_NAME, LAST_NAME, SALARY
FROM (
    SELECT FIRST_NAME, LAST_NAME, SALARY
    FROM EMPLOYEES
    ORDER BY SALARY DESC
     )
WHERE ROWNUM <= 7
ORDER BY SALARY