DROP TABLE SONG CASCADE CONSTRAINTS;
DROP TABLE PURCHASE CASCADE CONSTRAINTS;
DROP TABLE STOCK CASCADE CONSTRAINTS;
DROP TABLE CUSTOMER CASCADE CONSTRAINTS;
DROP TABLE EMPLOYEE CASCADE CONSTRAINTS;
DROP TABLE FUNCTION CASCADE CONSTRAINTS;
DROP TABLE MEDIA_FORMAT CASCADE CONSTRAINTS;
DROP TABLE PROVIDER CASCADE CONSTRAINTS;
DROP TABLE ARTIST CASCADE CONSTRAINTS;
DROP TABLE GENRE CASCADE CONSTRAINTS;
DROP TABLE MERCHANDISE CASCADE CONSTRAINTS;
DROP TABLE ALBUM CASCADE CONSTRAINTS;
DROP TABLE PRODUCT CASCADE CONSTRAINTS;
DROP TABLE RECORD_LABEL CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_RECORD_LABEL;
DROP SEQUENCE SEQ_PRODUCT;
DROP SEQUENCE SEQ_GENRE;
DROP SEQUENCE SEQ_ARTIST;
DROP SEQUENCE SEQ_PROVIDER;
DROP SEQUENCE SEQ_MEDIA_FORMAT;
DROP SEQUENCE SEQ_FUNCTION;
DROP SEQUENCE SEQ_EMPLOYEE;
DROP SEQUENCE SEQ_CUSTOMER;
DROP SEQUENCE SEQ_STOCK;
DROP SEQUENCE SEQ_PURCHASE;
DROP SEQUENCE SEQ_SONG;

